/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Index;
import Pedidos.*;
import Registros.RegistroCliente;
import Registros.RegistroPersonalSistema;

/**
 *
 * @author EdilsonJMT
 */
public class Index extends javax.swing.JFrame {
    

    /**
     * Creates new form LoginSesion
     */
    public Index() {
        initComponents();
        this.setLocationRelativeTo(null);
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackGround = new javax.swing.JPanel();
        AzulLateral = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BotonBebidaGrande = new javax.swing.JButton();
        BotonPedido = new javax.swing.JButton();
        BotonClientes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BackGround.setBackground(new java.awt.Color(255, 255, 255));
        BackGround.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AzulLateral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesCineplanet/FondoWallpaperV3.png"))); // NOI18N
        BackGround.add(AzulLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 720));

        jLabel1.setFont(new java.awt.Font("SansSerif", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Seleccione una accion.");
        BackGround.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 1110, 100));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesCineplanet/TexturaRosaCabeceraV1.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        BackGround.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 1110, -1));

        BotonBebidaGrande.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        BotonBebidaGrande.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesCineplanet/PersonalV1.png"))); // NOI18N
        BotonBebidaGrande.setText("CREAR /EDITAR /ELIMINAR PERSONAL");
        BotonBebidaGrande.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBebidaGrandeActionPerformed(evt);
            }
        });
        BackGround.add(BotonBebidaGrande, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 540, 1000, 150));

        BotonPedido.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        BotonPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesCineplanet/NuevoPedidov2.png"))); // NOI18N
        BotonPedido.setText("REALIZAR UN PEDIDO");
        BotonPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPedidoActionPerformed(evt);
            }
        });
        BackGround.add(BotonPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 1000, 150));

        BotonClientes.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        BotonClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesCineplanet/UsuarioV1.png"))); // NOI18N
        BotonClientes.setText("CREAR /EDITAR /ELIMINAR CLIENTES");
        BotonClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonClientesActionPerformed(evt);
            }
        });
        BackGround.add(BotonClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 1000, 150));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGround, javax.swing.GroupLayout.PREFERRED_SIZE, 1280, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BackGround, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPedidoActionPerformed
                    PedidoSesion form=new PedidoSesion();
                    form.setVisible(true);
                    this.dispose();
    }//GEN-LAST:event_BotonPedidoActionPerformed

    private void BotonClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonClientesActionPerformed
                    RegistroCliente form=new RegistroCliente();
                    form.setVisible(true);
                    this.dispose();
    }//GEN-LAST:event_BotonClientesActionPerformed

    private void BotonBebidaGrandeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBebidaGrandeActionPerformed
                    RegistroPersonalSistema form=new RegistroPersonalSistema();
                    form.setVisible(true);
                    this.dispose();
    }//GEN-LAST:event_BotonBebidaGrandeActionPerformed

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AzulLateral;
    private javax.swing.JPanel BackGround;
    private javax.swing.JButton BotonBebidaGrande;
    private javax.swing.JButton BotonClientes;
    private javax.swing.JButton BotonPedido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
