/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pedidos;
import Index.Index;
import com.mysql.jdbc.PreparedStatement;
import conexion.ConexionBD;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author EdilsonJMT
 */
public class PedidoSesion extends javax.swing.JFrame {
    
        ConexionBD cnxn = new ConexionBD();
        Connection cn = cnxn.conectar();
        
            public SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            Date dia = new Date();
            String fecha = sdf.format(dia);
            int Total=0;
            int Fila=0;

    /**
     * Creates new form LoginSesion
     */
    public PedidoSesion() {
        initComponents();
        this.setLocationRelativeTo(null);
        MostrarDatos();
        LimpiarTotal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackGround = new javax.swing.JPanel();
        AzulLateral = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BotonCanchaGigante = new javax.swing.JButton();
        BotonCanchaMediana = new javax.swing.JButton();
        BotonCanchaGrande = new javax.swing.JButton();
        BotonBebidaGrande = new javax.swing.JButton();
        BotonAguaMineral = new javax.swing.JButton();
        BotonBebidaMediana = new javax.swing.JButton();
        BotonCombo = new javax.swing.JButton();
        BotonNachos = new javax.swing.JButton();
        BotonHotDog = new javax.swing.JButton();
        txtCodCliente = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        BotonIniciarPedido = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaVista = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txtCodPed = new javax.swing.JTextField();
        txtCodUsuario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        BotonEliminarProducto = new javax.swing.JButton();
        BotonActualizar = new javax.swing.JButton();
        BotonEliminarPedido = new javax.swing.JButton();
        BotonRegresarInicio = new javax.swing.JButton();
        txtTotal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BackGround.setBackground(new java.awt.Color(255, 255, 255));
        BackGround.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AzulLateral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesCineplanet/FondoWallpaperV3.png"))); // NOI18N
        BackGround.add(AzulLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 720));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesCineplanet/TexturaRosaCabeceraV1.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        BackGround.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 1110, 50));

        BotonCanchaGigante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesCineplanet/CanchaGiganteV1.png"))); // NOI18N
        BotonCanchaGigante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCanchaGiganteActionPerformed(evt);
            }
        });
        BackGround.add(BotonCanchaGigante, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 150, 150, 150));

        BotonCanchaMediana.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesCineplanet/CanchitaMedianaV1.png"))); // NOI18N
        BotonCanchaMediana.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        BotonCanchaMediana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCanchaMedianaActionPerformed(evt);
            }
        });
        BackGround.add(BotonCanchaMediana, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 150, 150));

        BotonCanchaGrande.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesCineplanet/CanchaGrandeV1.png"))); // NOI18N
        BotonCanchaGrande.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCanchaGrandeActionPerformed(evt);
            }
        });
        BackGround.add(BotonCanchaGrande, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, 150, 150));

        BotonBebidaGrande.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesCineplanet/BebidaGrande.png"))); // NOI18N
        BotonBebidaGrande.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBebidaGrandeActionPerformed(evt);
            }
        });
        BackGround.add(BotonBebidaGrande, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 340, 150, 150));

        BotonAguaMineral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesCineplanet/AguaMineral.png"))); // NOI18N
        BotonAguaMineral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAguaMineralActionPerformed(evt);
            }
        });
        BackGround.add(BotonAguaMineral, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, 150, 150));

        BotonBebidaMediana.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesCineplanet/BebidaMediana.png"))); // NOI18N
        BotonBebidaMediana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBebidaMedianaActionPerformed(evt);
            }
        });
        BackGround.add(BotonBebidaMediana, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 150, 150));

        BotonCombo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesCineplanet/Combov1.png"))); // NOI18N
        BotonCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonComboActionPerformed(evt);
            }
        });
        BackGround.add(BotonCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 530, 150, 150));

        BotonNachos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesCineplanet/Nachos.png"))); // NOI18N
        BotonNachos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonNachosActionPerformed(evt);
            }
        });
        BackGround.add(BotonNachos, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 530, 150, 150));

        BotonHotDog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesCineplanet/HotDog.png"))); // NOI18N
        BotonHotDog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonHotDogActionPerformed(evt);
            }
        });
        BackGround.add(BotonHotDog, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 530, 150, 150));

        txtCodCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodClienteActionPerformed(evt);
            }
        });
        BackGround.add(txtCodCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 100, 150, 30));

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel1.setText("Cliente:");
        BackGround.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 60, 130, 30));

        BotonIniciarPedido.setBackground(new java.awt.Color(0, 51, 153));
        BotonIniciarPedido.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        BotonIniciarPedido.setForeground(new java.awt.Color(255, 255, 255));
        BotonIniciarPedido.setText("Generar Pedido");
        BotonIniciarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonIniciarPedidoActionPerformed(evt);
            }
        });
        BackGround.add(BotonIniciarPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 70, 130, 30));

        TablaVista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(TablaVista);

        BackGround.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 110, 480, 240));

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel3.setText("Codigo de Pedido :");
        BackGround.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 130, 30));

        txtCodPed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodPedActionPerformed(evt);
            }
        });
        BackGround.add(txtCodPed, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 150, 30));

        txtCodUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodUsuarioActionPerformed(evt);
            }
        });
        BackGround.add(txtCodUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 150, 30));

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel4.setText("Encargado:");
        BackGround.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 130, 30));

        BotonEliminarProducto.setBackground(new java.awt.Color(0, 51, 153));
        BotonEliminarProducto.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        BotonEliminarProducto.setForeground(new java.awt.Color(255, 255, 255));
        BotonEliminarProducto.setText("Eliminar Producto");
        BotonEliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEliminarProductoActionPerformed(evt);
            }
        });
        BackGround.add(BotonEliminarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 360, 140, 30));

        BotonActualizar.setBackground(new java.awt.Color(0, 51, 153));
        BotonActualizar.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        BotonActualizar.setForeground(new java.awt.Color(255, 255, 255));
        BotonActualizar.setText("Actualizar Tabla");
        BotonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonActualizarActionPerformed(evt);
            }
        });
        BackGround.add(BotonActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 360, 140, 30));

        BotonEliminarPedido.setBackground(new java.awt.Color(0, 51, 153));
        BotonEliminarPedido.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        BotonEliminarPedido.setForeground(new java.awt.Color(255, 255, 255));
        BotonEliminarPedido.setText("Eliminar Pedido");
        BotonEliminarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEliminarPedidoActionPerformed(evt);
            }
        });
        BackGround.add(BotonEliminarPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 360, 140, 30));

        BotonRegresarInicio.setBackground(new java.awt.Color(0, 51, 153));
        BotonRegresarInicio.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        BotonRegresarInicio.setForeground(new java.awt.Color(255, 255, 255));
        BotonRegresarInicio.setText("Regresar al Inicio");
        BotonRegresarInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegresarInicioActionPerformed(evt);
            }
        });
        BackGround.add(BotonRegresarInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 70, 140, 30));

        txtTotal.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });
        BackGround.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 440, 150, 50));

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesCineplanet/Dinerov1.png"))); // NOI18N
        jLabel6.setText(" Total a pagar:");
        BackGround.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 440, 170, 50));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesCineplanet/LogoCPLargo.png"))); // NOI18N
        BackGround.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 560, 370, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGround, javax.swing.GroupLayout.PREFERRED_SIZE, 1280, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BackGround, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void BotonRegresarInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegresarInicioActionPerformed
        Index form=new Index();
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotonRegresarInicioActionPerformed

    private void BotonEliminarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEliminarPedidoActionPerformed
        EliminarID();
        EliminarPedido();
        MostrarDatos();
    }//GEN-LAST:event_BotonEliminarPedidoActionPerformed

    private void BotonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonActualizarActionPerformed
        MostrarDatos();
    }//GEN-LAST:event_BotonActualizarActionPerformed

    private void BotonEliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEliminarProductoActionPerformed
        EliminarPersonal();
        SumarColumna();
        MostrarDatos();
        LimpiarTotal();
    }//GEN-LAST:event_BotonEliminarProductoActionPerformed

    private void txtCodUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodUsuarioActionPerformed

    private void txtCodPedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodPedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodPedActionPerformed

    private void BotonIniciarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonIniciarPedidoActionPerformed
        try {
            PreparedStatement ps = (PreparedStatement) cn.prepareStatement("INSERT INTO `pedidocp` (`id_pedido`, `fecha_ped`, `importe`, `total`,`resto`,`id_per`, `id_cli`) VALUES ('" + txtCodPed.getText() + "','"+fecha+"', '0','0','0','" + txtCodUsuario.getText() + "','" + txtCodCliente.getText() + "');");
            ps.executeUpdate();
            MostrarDatos();
        } catch (Exception e) {
            System.out.println("Error:" + e);
        }
    }//GEN-LAST:event_BotonIniciarPedidoActionPerformed

    private void txtCodClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodClienteActionPerformed

    private void BotonHotDogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonHotDogActionPerformed
        try {
            PreparedStatement ps = (PreparedStatement) cn.prepareStatement("INSERT INTO `productoseleccion` (`id_seleccion`, `precio`, `id_producto`, `id_pedido`) VALUES (NULL, '13', '1021','" + txtCodPed.getText()+ "');");
            ps.executeUpdate();
            MostrarDatos();
        } catch (Exception e) {
            System.out.println("Error:" + e);
        }
        SumaTotal(13);
    }//GEN-LAST:event_BotonHotDogActionPerformed

    private void BotonNachosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonNachosActionPerformed
        try {
            PreparedStatement ps = (PreparedStatement) cn.prepareStatement("INSERT INTO `productoseleccion` (`id_seleccion`, `precio`, `id_producto`, `id_pedido`) VALUES (NULL, '13', '1020','" + txtCodPed.getText()+ "');");
            ps.executeUpdate();
            MostrarDatos();
        } catch (Exception e) {
            System.out.println("Error:" + e);
        }
        SumaTotal(13);
    }//GEN-LAST:event_BotonNachosActionPerformed

    private void BotonComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonComboActionPerformed
        try {
            PreparedStatement ps = (PreparedStatement) cn.prepareStatement("INSERT INTO `productoseleccion` (`id_seleccion`, `precio`, `id_producto`, `id_pedido`) VALUES (NULL, '48', '1014','" + txtCodPed.getText()+ "');");
            ps.executeUpdate();
            MostrarDatos();
        } catch (Exception e) {
            System.out.println("Error:" + e);
        }
        SumaTotal(48);
    }//GEN-LAST:event_BotonComboActionPerformed

    private void BotonBebidaMedianaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBebidaMedianaActionPerformed
        try {
            PreparedStatement ps = (PreparedStatement) cn.prepareStatement("INSERT INTO `productoseleccion` (`id_seleccion`, `precio`, `id_producto`, `id_pedido`) VALUES (NULL, '12', '1017','" + txtCodPed.getText()+ "');");
            ps.executeUpdate();
            MostrarDatos();
        } catch (Exception e) {
            System.out.println("Error:" + e);
        }
        SumaTotal(12);
    }//GEN-LAST:event_BotonBebidaMedianaActionPerformed

    private void BotonAguaMineralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAguaMineralActionPerformed
        try {
            PreparedStatement ps = (PreparedStatement) cn.prepareStatement("INSERT INTO `productoseleccion` (`id_seleccion`, `precio`, `id_producto`, `id_pedido`) VALUES (NULL, '5', '1019','" + txtCodPed.getText()+ "');");
            ps.executeUpdate();
            MostrarDatos();
        } catch (Exception e) {
            System.out.println("Error:" + e);
        }
        SumaTotal(5);
    }//GEN-LAST:event_BotonAguaMineralActionPerformed

    private void BotonBebidaGrandeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBebidaGrandeActionPerformed
        try {
            PreparedStatement ps = (PreparedStatement) cn.prepareStatement("INSERT INTO `productoseleccion` (`id_seleccion`, `precio`, `id_producto`, `id_pedido`) VALUES (NULL, '14', '1018','" + txtCodPed.getText()+ "');");
            ps.executeUpdate();
            MostrarDatos();
        } catch (Exception e) {
            System.out.println("Error:" + e);
        }
        SumaTotal(14);
    }//GEN-LAST:event_BotonBebidaGrandeActionPerformed

    private void BotonCanchaGrandeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCanchaGrandeActionPerformed
        try {
            PreparedStatement ps = (PreparedStatement) cn.prepareStatement("INSERT INTO `productoseleccion` (`id_seleccion`, `precio`, `id_producto`, `id_pedido`) VALUES (NULL, '17', '1002','" + txtCodPed.getText()+ "');");
            ps.executeUpdate();
            MostrarDatos();
        } catch (Exception e) {
            System.out.println("Error:" + e);
        }
        SumaTotal(17);
    }//GEN-LAST:event_BotonCanchaGrandeActionPerformed

    private void BotonCanchaMedianaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCanchaMedianaActionPerformed
        try {
            PreparedStatement ps = (PreparedStatement) cn.prepareStatement("INSERT INTO `productoseleccion` (`id_seleccion`, `precio`, `id_producto`, `id_pedido`) VALUES (NULL, '14', '1000','" + txtCodPed.getText()+ "');");
            ps.executeUpdate();
            MostrarDatos();
        } catch (Exception e) {
            System.out.println("Error:" + e);
        }
        SumaTotal(14);
    }//GEN-LAST:event_BotonCanchaMedianaActionPerformed

    private void BotonCanchaGiganteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCanchaGiganteActionPerformed
        try {
            PreparedStatement ps = (PreparedStatement) cn.prepareStatement("INSERT INTO `productoseleccion` (`id_seleccion`, `precio`, `id_producto`, `id_pedido`) VALUES (NULL, '22', '1004','" + txtCodPed.getText()+ "');");
            ps.executeUpdate();
            MostrarDatos();
        } catch (Exception e) {
            System.out.println("Error:" + e);
        }
        SumaTotal(22);
    }//GEN-LAST:event_BotonCanchaGiganteActionPerformed

    public void MostrarDatos(){
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Id_Seleccion");
        modelo.addColumn("Precio");
        modelo.addColumn("Id_Producto");
        modelo.addColumn("Id_Pedido");
        TablaVista.setModel(modelo);
        String sql = "select * from productoseleccion";
        String[] Registros=new String[4];
        
        Statement st;
        try {

            st = (Statement) cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                Registros[0] = rs.getString(1);
                Registros[1] = rs.getString(2);
                Registros[2] = rs.getString(3);
                Registros[3] = rs.getString(4);
                modelo.addRow(Registros);
            }

        } catch (SQLException e) {
            System.out.println("Error al mostrar los datos:" + e);
        }
    }
    
    public void EliminarPersonal() {
        int FilaOpcion=TablaVista.getSelectedRow();
        try{
            String SQL="delete from productoseleccion where id_seleccion='" +TablaVista.getValueAt(FilaOpcion,0)+ "'";
            Statement st=cn.createStatement();
            
            int n=st.executeUpdate(SQL);
            
            if (n>=0){
                
            }
        } catch (Exception e){
            JOptionPane.showMessageDialog(null,"Error al eliminar" +e.getMessage());
            
        }
    }
        
    public void EliminarID() {
        try{
            String SQL="delete from productoseleccion where id_pedido='" +txtCodPed.getText()+ "'";
            Statement st=cn.createStatement();
            
            int n=st.executeUpdate(SQL);
            
            if (n>=0){
                JOptionPane.showMessageDialog(null,"Pedido Eliminado");
                
            }
        } catch (Exception e){
            JOptionPane.showMessageDialog(null,"Error al eliminar" +e.getMessage());
            
        }
    }
    
    public void EliminarPedido() {
        try{
            String SQL="delete from pedidocp where id_pedido='" +txtCodPed.getText()+ "'";
            Statement st=cn.createStatement();
            
            int n=st.executeUpdate(SQL);
            
            if (n>=0){
                
            }
        } catch (Exception e){
            JOptionPane.showMessageDialog(null,"Error al eliminar" +e.getMessage());
            
        }
    }
        
    public void LimpiarCajas() {
        txtCodPed.setText("");
        txtCodUsuario.setText("");
        txtCodCliente.setText("");

    }
    
    public void LimpiarTotal(){
        txtTotal.setText("");
        SumarColumna();
    }
    
    public void SumaTotal(int num){
        Total = Total + num;
        txtTotal.setText(String.valueOf(Total));
    }
    
    public void SumarColumna() {
        Total = 0;

        for (int i = 0; i < TablaVista.getRowCount(); i++) {

            Fila = Integer.parseInt(TablaVista.getValueAt(i, 1).toString());
            Total = Total + Fila;
            txtTotal.setText(String.valueOf(Total));
        }

    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PedidoSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PedidoSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PedidoSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PedidoSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PedidoSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AzulLateral;
    private javax.swing.JPanel BackGround;
    private javax.swing.JButton BotonActualizar;
    private javax.swing.JButton BotonAguaMineral;
    private javax.swing.JButton BotonBebidaGrande;
    private javax.swing.JButton BotonBebidaMediana;
    private javax.swing.JButton BotonCanchaGigante;
    private javax.swing.JButton BotonCanchaGrande;
    private javax.swing.JButton BotonCanchaMediana;
    private javax.swing.JButton BotonCombo;
    private javax.swing.JButton BotonEliminarPedido;
    private javax.swing.JButton BotonEliminarProducto;
    private javax.swing.JButton BotonHotDog;
    private javax.swing.JButton BotonIniciarPedido;
    private javax.swing.JButton BotonNachos;
    private javax.swing.JButton BotonRegresarInicio;
    private javax.swing.JTable TablaVista;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCodCliente;
    private javax.swing.JTextField txtCodPed;
    private javax.swing.JTextField txtCodUsuario;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
