/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Registros;

import Index.Index;
import com.mysql.jdbc.PreparedStatement;
import conexion.ConexionBD;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author EdilsonJMT
 */
public class RegistroPersonalSistema extends javax.swing.JFrame {
    
    ConexionBD cc=new ConexionBD();
    Connection con=cc.conectar();

    
    /**
     * Creates new form LoginSesion
     */
    public RegistroPersonalSistema() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackGround = new javax.swing.JPanel();
        TextoContraseña = new javax.swing.JLabel();
        TextoCelular = new javax.swing.JLabel();
        TextoDNI = new javax.swing.JLabel();
        TextoApellido = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        TextoCorreo1 = new javax.swing.JLabel();
        jSeparator14 = new javax.swing.JSeparator();
        BotonRegistrarse = new javax.swing.JButton();
        BotonRegresar = new javax.swing.JButton();
        TextoNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtDNI = new javax.swing.JTextField();
        txtCelular = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        txtContraseña = new javax.swing.JPasswordField();
        txtCodigo = new javax.swing.JTextField();
        TextoCodigo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Cabezera = new javax.swing.JLabel();
        BotonEditar = new javax.swing.JButton();
        BotonBorrar = new javax.swing.JButton();
        BotonActualizar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaPersonal = new javax.swing.JTable();
        TexturaBlanca = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BackGround.setBackground(new java.awt.Color(255, 255, 255));
        BackGround.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextoContraseña.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        TextoContraseña.setText("Contraseña:");
        TextoContraseña.setToolTipText("");
        BackGround.add(TextoContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 370, 30));

        TextoCelular.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        TextoCelular.setText("Celular:");
        TextoCelular.setToolTipText("");
        BackGround.add(TextoCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 370, 370, 30));

        TextoDNI.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        TextoDNI.setText("DNI:");
        TextoDNI.setToolTipText("");
        BackGround.add(TextoDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 370, 30));

        TextoApellido.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        TextoApellido.setText("Apellido:");
        TextoApellido.setToolTipText("");
        BackGround.add(TextoApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, 370, 30));

        jSeparator8.setForeground(new java.awt.Color(102, 102, 102));
        BackGround.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 350, 20));

        jSeparator9.setForeground(new java.awt.Color(102, 102, 102));
        BackGround.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, 350, 20));

        jSeparator10.setForeground(new java.awt.Color(102, 102, 102));
        BackGround.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 440, 350, 20));

        jSeparator12.setForeground(new java.awt.Color(102, 102, 102));
        BackGround.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 350, 20));

        jSeparator13.setForeground(new java.awt.Color(102, 102, 102));
        BackGround.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 350, 20));

        TextoCorreo1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        TextoCorreo1.setText("Correo:");
        TextoCorreo1.setToolTipText("");
        BackGround.add(TextoCorreo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 370, 30));

        jSeparator14.setForeground(new java.awt.Color(102, 102, 102));
        BackGround.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, 350, 20));

        BotonRegistrarse.setBackground(new java.awt.Color(0, 51, 153));
        BotonRegistrarse.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        BotonRegistrarse.setForeground(new java.awt.Color(255, 255, 255));
        BotonRegistrarse.setText("Registrar");
        BotonRegistrarse.setBorder(null);
        BotonRegistrarse.setBorderPainted(false);
        BotonRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegistrarseActionPerformed(evt);
            }
        });
        BackGround.add(BotonRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 570, 130, 50));

        BotonRegresar.setBackground(new java.awt.Color(0, 51, 153));
        BotonRegresar.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        BotonRegresar.setForeground(new java.awt.Color(255, 255, 255));
        BotonRegresar.setText("Regresar al incio");
        BotonRegresar.setBorder(null);
        BotonRegresar.setBorderPainted(false);
        BotonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegresarActionPerformed(evt);
            }
        });
        BackGround.add(BotonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 570, 130, 50));

        TextoNombre.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        TextoNombre.setText("Nombre:");
        TextoNombre.setToolTipText("");
        BackGround.add(TextoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 370, 30));
        BackGround.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 350, 30));
        BackGround.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, 350, 30));
        BackGround.add(txtDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 350, 30));
        BackGround.add(txtCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 400, 350, 30));
        BackGround.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 350, 30));

        jSeparator5.setForeground(new java.awt.Color(102, 102, 102));
        BackGround.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 350, 20));
        BackGround.add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 350, 30));
        BackGround.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 350, 30));

        TextoCodigo.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        TextoCodigo.setText("Usuario:");
        TextoCodigo.setToolTipText("");
        BackGround.add(TextoCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 370, 30));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REGISTRO DE PERSONAL");
        BackGround.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 100));

        Cabezera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesCineplanet/CabeceraVF.png"))); // NOI18N
        BackGround.add(Cabezera, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 100));

        BotonEditar.setBackground(new java.awt.Color(0, 51, 153));
        BotonEditar.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        BotonEditar.setForeground(new java.awt.Color(255, 255, 255));
        BotonEditar.setText("Editar");
        BotonEditar.setBorder(null);
        BotonEditar.setBorderPainted(false);
        BotonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEditarActionPerformed(evt);
            }
        });
        BackGround.add(BotonEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 570, 130, 50));

        BotonBorrar.setBackground(new java.awt.Color(0, 51, 153));
        BotonBorrar.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        BotonBorrar.setForeground(new java.awt.Color(255, 255, 255));
        BotonBorrar.setText("Borrar");
        BotonBorrar.setBorder(null);
        BotonBorrar.setBorderPainted(false);
        BotonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBorrarActionPerformed(evt);
            }
        });
        BackGround.add(BotonBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 570, 130, 50));

        BotonActualizar.setBackground(new java.awt.Color(0, 51, 153));
        BotonActualizar.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        BotonActualizar.setForeground(new java.awt.Color(255, 255, 255));
        BotonActualizar.setText(" Actualizar tabla");
        BotonActualizar.setBorder(null);
        BotonActualizar.setBorderPainted(false);
        BotonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonActualizarActionPerformed(evt);
            }
        });
        BackGround.add(BotonActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 570, 130, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesCineplanet/LogoCPLargo.png"))); // NOI18N
        BackGround.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 480, 340, 70));

        TablaPersonal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TablaPersonal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaPersonalMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaPersonal);

        BackGround.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 160, 520, 400));

        TexturaBlanca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesCineplanet/FondoBlancoGigante.png"))); // NOI18N
        BackGround.add(TexturaBlanca, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1280, 620));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGround, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegistrarseActionPerformed
        try {
            InsertarPersonal();
            LimpiarCajas();
            MostrarDatos();
        } catch (SQLException ex) {
            Logger.getLogger(RegistroPersonalSistema.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BotonRegistrarseActionPerformed

    private void BotonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegresarActionPerformed
                    Index form=new Index();
                    form.setVisible(true);
                    this.dispose();
    }//GEN-LAST:event_BotonRegresarActionPerformed

    private void BotonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEditarActionPerformed
        try {
            EditarPersonal();
            LimpiarCajas();
            MostrarDatos();
        } catch (SQLException ex) {
            Logger.getLogger(RegistroPersonalSistema.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_BotonEditarActionPerformed

    private void BotonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBorrarActionPerformed

            EliminarPersonal();
            LimpiarCajas();
            MostrarDatos();
        

    }//GEN-LAST:event_BotonBorrarActionPerformed

    private void BotonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonActualizarActionPerformed
        MostrarDatos();
        LimpiarCajas();
    }//GEN-LAST:event_BotonActualizarActionPerformed

    private void TablaPersonalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaPersonalMouseClicked
        int FilaSeleccion=TablaPersonal.rowAtPoint(evt.getPoint());
        txtCodigo.setText(TablaPersonal.getValueAt(FilaSeleccion, 0).toString());
        txtNombre.setText(TablaPersonal.getValueAt(FilaSeleccion, 1).toString());
        txtApellido.setText(TablaPersonal.getValueAt(FilaSeleccion, 2).toString());
        txtDNI.setText(TablaPersonal.getValueAt(FilaSeleccion, 3).toString());
        txtCelular.setText(TablaPersonal.getValueAt(FilaSeleccion, 4).toString());
        txtCorreo.setText(TablaPersonal.getValueAt(FilaSeleccion, 5).toString());
        
    }//GEN-LAST:event_TablaPersonalMouseClicked

    public void InsertarPersonal() throws SQLException{
        try {
        String SQL="insert into personalcp (id_per, nombre_per, apellidos_per, dni_per, cel_per, email_per, contraseña) values(?,?,?,?,?,?,?)";
        PreparedStatement pst=(PreparedStatement) con.prepareStatement(SQL);
        
        pst.setString(1, txtCodigo.getText());
        pst.setString(2, txtNombre.getText());
        pst.setString(3, txtApellido.getText());
        pst.setString(4, txtDNI.getText());
        pst.setString(5, txtCelular.getText());
        pst.setString(6, txtCorreo.getText());
        pst.setString(7, txtContraseña.getText());
        pst.execute();
        JOptionPane.showMessageDialog(null,"Registro exitoso");
        
        } catch (Exception e){
            JOptionPane.showMessageDialog(null,"Error al registrarse" +e);
        }
    }
    
    public void EditarPersonal() throws SQLException{
        try {
        String SQL="update personalcp set nombre_per=?, apellidos_per=?, dni_per=?, cel_per=?, email_per=?, contraseña=? where id_per=?";
        int FilaSeleccionada=TablaPersonal.getSelectedRow();
        String dc=(String)TablaPersonal.getValueAt(FilaSeleccionada, 0);
        PreparedStatement pse=(PreparedStatement) con.prepareStatement(SQL);
        
        //pse.setString(1, txtCodigo.getText());
        pse.setString(1, txtNombre.getText());
        pse.setString(2, txtApellido.getText());
        pse.setString(3, txtDNI.getText());
        pse.setString(4, txtCelular.getText());
        pse.setString(5, txtCorreo.getText());
        pse.setString(6, txtContraseña.getText());
        pse.setString(7, dc);
        pse.execute();
        JOptionPane.showMessageDialog(null,"Actualizacion exitosa");
        
        } catch (Exception e){
            JOptionPane.showMessageDialog(null,"Error al Actualizar" +e);
        }
    }
    
    public void EliminarPersonal() {
        int FilaOpcion=TablaPersonal.getSelectedRow();
        try{
            String SQL="delete from personalcp where id_per='" +TablaPersonal.getValueAt(FilaOpcion,0)+ "'";
            Statement st=con.createStatement();
            
            int n=st.executeUpdate(SQL);
            
            if (n>=0){
                JOptionPane.showMessageDialog(null,"Personal Eliminado");
                
            }
        } catch (Exception e){
            JOptionPane.showMessageDialog(null,"Error al eliminar" +e.getMessage());
            
        }
    }
    
    public void LimpiarCajas() {
        txtCodigo.setText("");
        txtNombre.setText("");
        txtApellido.setText("");
        txtDNI.setText("");
        txtCelular.setText("");
        txtCorreo.setText("");
        txtContraseña.setText("");
    }
    
    public void MostrarDatos(){
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Usuario");
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellido");
        modelo.addColumn("DNI");
        modelo.addColumn("Celular");
        modelo.addColumn("Correo");
        modelo.addColumn("Contraseña");
        TablaPersonal.setModel(modelo);
        String sql = "select * from personalcp";
        String[] Registros=new String[7];
        
        Statement st;
        try {

            st = (Statement) con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                Registros[0] = rs.getString(1);
                Registros[1] = rs.getString(2);
                Registros[2] = rs.getString(3);
                Registros[3] = rs.getString(4);
                Registros[4] = rs.getString(5);
                Registros[5] = rs.getString(6);
                Registros[6] = rs.getString(7);
                modelo.addRow(Registros);
            }

        } catch (SQLException e) {
            System.out.println("Error al mostrar los datos:" + e);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroPersonalSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroPersonalSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroPersonalSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroPersonalSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroPersonalSistema().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackGround;
    private javax.swing.JButton BotonActualizar;
    private javax.swing.JButton BotonBorrar;
    private javax.swing.JButton BotonEditar;
    private javax.swing.JButton BotonRegistrarse;
    private javax.swing.JButton BotonRegresar;
    private javax.swing.JLabel Cabezera;
    private javax.swing.JTable TablaPersonal;
    private javax.swing.JLabel TextoApellido;
    private javax.swing.JLabel TextoCelular;
    private javax.swing.JLabel TextoCodigo;
    private javax.swing.JLabel TextoContraseña;
    private javax.swing.JLabel TextoCorreo1;
    private javax.swing.JLabel TextoDNI;
    private javax.swing.JLabel TextoNombre;
    private javax.swing.JLabel TexturaBlanca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
