/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Registros;

import LoginSesion.LoginSesion;
import com.mysql.jdbc.PreparedStatement;
import conexion.ConexionBD;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author EdilsonJMT
 */
public class RegistroPersonal extends javax.swing.JFrame {
    
    ConexionBD cc=new ConexionBD();
    Connection con=cc.conectar();

    
    /**
     * Creates new form LoginSesion
     */
    public RegistroPersonal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackGround = new javax.swing.JPanel();
        FondoWallpaper = new javax.swing.JPanel();
        FondoImagenWallpaper = new javax.swing.JLabel();
        TextoContraseña = new javax.swing.JLabel();
        TextoCorreo = new javax.swing.JLabel();
        TextoCelular = new javax.swing.JLabel();
        TextoDNI = new javax.swing.JLabel();
        TextoApellido = new javax.swing.JLabel();
        TextoNombre = new javax.swing.JLabel();
        BotonCancelar = new javax.swing.JButton();
        BotonRegistrarse = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtDNI = new javax.swing.JTextField();
        txtCelular = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        txtContraseña = new javax.swing.JPasswordField();
        jSeparator7 = new javax.swing.JSeparator();
        txtCodigo = new javax.swing.JTextField();
        TextoCodigo = new javax.swing.JLabel();
        Textura = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BackGround.setBackground(new java.awt.Color(255, 255, 255));
        BackGround.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FondoWallpaper.setBackground(new java.awt.Color(0, 51, 153));

        FondoImagenWallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesCineplanet/FondoWallpaperV3.png"))); // NOI18N

        javax.swing.GroupLayout FondoWallpaperLayout = new javax.swing.GroupLayout(FondoWallpaper);
        FondoWallpaper.setLayout(FondoWallpaperLayout);
        FondoWallpaperLayout.setHorizontalGroup(
            FondoWallpaperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FondoImagenWallpaper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        FondoWallpaperLayout.setVerticalGroup(
            FondoWallpaperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FondoImagenWallpaper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        BackGround.add(FondoWallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 900, 720));

        TextoContraseña.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        TextoContraseña.setText("Contraseña:");
        TextoContraseña.setToolTipText("");
        BackGround.add(TextoContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, 370, 30));

        TextoCorreo.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        TextoCorreo.setText("Correo:");
        TextoCorreo.setToolTipText("");
        BackGround.add(TextoCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 370, 30));

        TextoCelular.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        TextoCelular.setText("Celular:");
        TextoCelular.setToolTipText("");
        BackGround.add(TextoCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 370, 30));

        TextoDNI.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        TextoDNI.setText("DNI:");
        TextoDNI.setToolTipText("");
        BackGround.add(TextoDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 370, 30));

        TextoApellido.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        TextoApellido.setText("Apellido:");
        TextoApellido.setToolTipText("");
        BackGround.add(TextoApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 370, 30));

        TextoNombre.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        TextoNombre.setText("Nombre:");
        TextoNombre.setToolTipText("");
        BackGround.add(TextoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 370, 30));

        BotonCancelar.setBackground(new java.awt.Color(0, 51, 153));
        BotonCancelar.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        BotonCancelar.setForeground(new java.awt.Color(255, 255, 255));
        BotonCancelar.setText("Cancelar");
        BotonCancelar.setBorder(null);
        BotonCancelar.setBorderPainted(false);
        BotonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCancelarActionPerformed(evt);
            }
        });
        BackGround.add(BotonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 630, 160, 50));

        BotonRegistrarse.setBackground(new java.awt.Color(0, 51, 153));
        BotonRegistrarse.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        BotonRegistrarse.setForeground(new java.awt.Color(255, 255, 255));
        BotonRegistrarse.setText("Registrarse");
        BotonRegistrarse.setBorder(null);
        BotonRegistrarse.setBorderPainted(false);
        BotonRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegistrarseActionPerformed(evt);
            }
        });
        BackGround.add(BotonRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 630, 160, 50));
        BackGround.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 350, 30));
        BackGround.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 350, 30));
        BackGround.add(txtDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 350, 30));
        BackGround.add(txtCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 350, 30));
        BackGround.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 350, 30));

        jSeparator1.setForeground(new java.awt.Color(102, 102, 102));
        BackGround.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 350, 20));

        jSeparator2.setForeground(new java.awt.Color(102, 102, 102));
        BackGround.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 350, 20));

        jSeparator3.setForeground(new java.awt.Color(102, 102, 102));
        BackGround.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 350, 20));

        jSeparator4.setForeground(new java.awt.Color(102, 102, 102));
        BackGround.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 600, 350, 20));

        jSeparator5.setForeground(new java.awt.Color(102, 102, 102));
        BackGround.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 350, 20));

        jSeparator6.setForeground(new java.awt.Color(102, 102, 102));
        BackGround.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 350, 20));
        BackGround.add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, 350, 30));

        jSeparator7.setForeground(new java.awt.Color(102, 102, 102));
        BackGround.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 350, 20));
        BackGround.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 350, 30));

        TextoCodigo.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        TextoCodigo.setText("Usuario:");
        TextoCodigo.setToolTipText("");
        BackGround.add(TextoCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 370, 30));

        Textura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesCineplanet/TexturaBlancoV1.png"))); // NOI18N
        BackGround.add(Textura, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGround, javax.swing.GroupLayout.PREFERRED_SIZE, 1280, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGround, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCancelarActionPerformed
        LoginSesion form=new LoginSesion();
                    form.setVisible(true);
                    this.dispose();
    }//GEN-LAST:event_BotonCancelarActionPerformed

    private void BotonRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegistrarseActionPerformed
        try {
            InsertarPersonal();
            LoginSesion form=new LoginSesion();
                    form.setVisible(true);
                    this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(RegistroPersonal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_BotonRegistrarseActionPerformed

    public void InsertarPersonal() throws SQLException{
        try {
        String SQL="insert into personalcp (id_per, nombre_per, apellidos_per, dni_per, cel_per, email_per, contraseña) values(?,?,?,?,?,?,?)";
        PreparedStatement pst=(PreparedStatement) con.prepareStatement(SQL);
        
        pst.setString(1, txtCodigo.getText());
        pst.setString(2, txtNombre.getText());
        pst.setString(3, txtApellido.getText());
        pst.setString(4, txtDNI.getText());
        pst.setString(5, txtCelular.getText());
        pst.setString(6, txtCorreo.getText());
        pst.setString(7, txtContraseña.getText());
        pst.execute();
        JOptionPane.showMessageDialog(null,"Registro exitoso");
        
        } catch (Exception e){
            JOptionPane.showMessageDialog(null,"Error al registrarse" +e);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroPersonal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackGround;
    private javax.swing.JButton BotonCancelar;
    private javax.swing.JButton BotonRegistrarse;
    private javax.swing.JLabel FondoImagenWallpaper;
    private javax.swing.JPanel FondoWallpaper;
    private javax.swing.JLabel TextoApellido;
    private javax.swing.JLabel TextoCelular;
    private javax.swing.JLabel TextoCodigo;
    private javax.swing.JLabel TextoContraseña;
    private javax.swing.JLabel TextoCorreo;
    private javax.swing.JLabel TextoDNI;
    private javax.swing.JLabel TextoNombre;
    private javax.swing.JLabel Textura;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
